# Generated by Django 4.1.7 on 2023-02-14 22:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(help_text='000-000-0000 (Without the dashes)', max_length=10, unique=True)),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='RentalPlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter the name of the Hotel', max_length=200)),
                ('street', models.CharField(help_text='Enter the name of the street', max_length=200)),
                ('description', models.TextField(help_text='Enter a brief description of the place', max_length=1000)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.owner')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this particular room accross the reservation website', primary_key=True, serialize=False)),
                ('due_back', models.DateField(blank=True, null=True)),
                ('cost', models.IntegerField(blank=True, help_text='Enter the cost of the room for one night', null=True)),
                ('is_premium', models.BooleanField(help_text='If the room is for premium clients')),
                ('status', models.CharField(blank=True, choices=[('d', 'Maintenance'), ('o', 'Booked'), ('a', 'Available'), ('r', 'Reserved')], default='d', help_text='Room availability', max_length=1)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('rental_place', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='catalog.rentalplace')),
            ],
        ),
    ]
